### ISSUE TITLE
bug line 32

### ISSUE THREAD

**Issue by RonyValle** [mannd00/week8#1]
Hello,
I tried out your script and got a few bugs.
on line 13 the script went crazy and I had to abort your script and delete that line in order to run the
variables part(good job with that part)
There was another bug I found on line 32:
echo "Well Hello There $MY_NAME" >> ${MY_NAME}_file 
The above line is your original code from line 32.
I think what you are trying to do is echo something into the file, but it didn't work for me. I had to make the following changes in order to get the desire results: 
echo "Well Hello There $MY_NAME" >> "${MY_NAME}_file"
I hope this helps!

**Comment by mannd00** [comment]
Hi!

Yeah, the first half of that was just playing around with the passwd and shadow files. The variables section was testing taking user input, saving to a variable and putting it in a file.
My my system it worked with an without the quotes" around ${MY_NAME}_file. maybe putting it in quotes is better practice and cross compatible. 

Thanks for the input!
