### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by EmanMac** [mannd00/week8#3]
You have those \n linebreaks in your echoes. Putting echo -e will make the quotation read line breaks. 

echo -e "We will check what user's folders are in /home and craete a service to perform backups. \n"

**Comment by mannd00** [comment]
Thanks for showing me the -e argument for echo! That enables interpretation of bashslash \ escape characters. Seems on my home system it is enabled by default.

Added that -e in and should work now.

Thank you.
